services:
  accounts:
    image: artellas/accounts:1
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce-ms
  loans:
    image: artellas/loans:1
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce-ms
  cards:
    image: artellas/cards:1
    container_name: cards-ms
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce-ms

networks:
  ecommerce-ms:
    driver: bridge