apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardsdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardsdb
  template:
    metadata:
      labels:
        app: cardsdb
    spec:
      containers:
        - name: cardsdb
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: cardsdb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: cardsdb-storage
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: cardsdb-storage
          persistentVolumeClaim:
            claimName: cardsdb-pvc
        - name: initdb
          configMap:
            name: cardsdb-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cardsdb-init
data:
  cards-schema.sql: |-
    CREATE TABLE IF NOT EXISTS `cards` (
      `card_id` int NOT NULL AUTO_INCREMENT,
      `mobile_number` varchar(15) NOT NULL,
      `card_number` varchar(100) NOT NULL,
      `card_type` varchar(100) NOT NULL,
      `total_limit` int NOT NULL,
      `amount_used` int NOT NULL,
      `available_amount` int NOT NULL,
      `created_at` date NOT NULL,
      `created_by` varchar(20) NOT NULL,
      `updated_at` date DEFAULT NULL,
      `updated_by` varchar(20) DEFAULT NULL,
      PRIMARY KEY (`card_id`)
    );
---
apiVersion: v1
kind: Service
metadata:
  name: cardsdb
spec:
  selector:
    app: cardsdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
