services:
  accountsdb:
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yaml
      service: microservice-db-config
    volumes:
      - ../../volumes/scripts/accounts-schema.sql:/docker-entrypoint-initdb.d/accounts-schema.sql
      - ../../volumes/default/accountsdb:/var/lib/mysql

  loansdb:
    container_name: loansdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yaml
      service: microservice-db-config
    volumes:
      - ../../volumes/scripts/loans-schema.sql:/docker-entrypoint-initdb.d/loans-schema.sql
      - ../../volumes/default/loansdb:/var/lib/mysql

  cardsdb:
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yaml
      service: microservice-db-config
    volumes:
      - ../../volumes/scripts/cards-schema.sql:/docker-entrypoint-initdb.d/cards-schema.sql
      - ../../volumes/default/cardsdb:/var/lib/mysql

  configserver:
    image: artellas/configserver:3
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  accounts:
    image: artellas/accounts:3
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: jdbc:mysql://accountsdb:3306/accountsdb
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  loans:
    image: artellas/loans:3
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: jdbc:mysql://loansdb:3306/loansdb
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  cards:
    image: artellas/cards:3
    container_name: cards-ms
    ports:
      - "8091:8091"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: jdbc:mysql://cardsdb:3306/cardsdb
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

networks:
  ecommerce-ms:
    driver: bridge