apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loansdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loansdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loansdb
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
        - name: loansdb
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: loansdb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: loansdb-storage
              mountPath: /var/lib/mysql
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: loansdb-storage
          persistentVolumeClaim:
            claimName: loansdb-pvc
        - name: initdb
          configMap:
            name: loansdb-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loansdb-init
data:
  loans-schema.sql: |-
    CREATE TABLE IF NOT EXISTS `loans` (
      `loan_id` int NOT NULL AUTO_INCREMENT,
      `mobile_number` varchar(15) NOT NULL,
      `loan_number` varchar(100) NOT NULL,
      `loan_type` varchar(100) NOT NULL,
      `total_loan` int NOT NULL,
      `amount_paid` int NOT NULL,
      `outstanding_amount` int NOT NULL,
      `created_at` date NOT NULL,
      `created_by` varchar(20) NOT NULL,
      `updated_at` date DEFAULT NULL,
      `updated_by` varchar(20) DEFAULT NULL,
      PRIMARY KEY (`loan_id`)
    );
---
apiVersion: v1
kind: Service
metadata:
  name: loansdb
spec:
  selector:
    app: loansdb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
