# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: artellas/cards
  tag: 8

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
datasource_url: jdbc:mysql://cardsdb:3306/cardsdb

cardsdb:
  enabled: true
  name: cardsdb
  pvcName: cardsdb-pvc
  storage: 1Gi
  image:
    repository: mysql
    tag: 8
  rootPassword: root
  database: cardsdb
  schema: |
    CREATE TABLE IF NOT EXISTS `cards` (
      `card_id` int NOT NULL AUTO_INCREMENT,
      `mobile_number` varchar(15) NOT NULL,
      `card_number` varchar(100) NOT NULL,
      `card_type` varchar(100) NOT NULL,
      `total_limit` int NOT NULL,
      `amount_used` int NOT NULL,
      `available_amount` int NOT NULL,
      `created_at` date NOT NULL,
      `created_by` varchar(20) NOT NULL,
      `updated_at` date DEFAULT NULL,
      `updated_by` varchar(20) DEFAULT NULL,
      PRIMARY KEY (`card_id`)
    );