# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: artellas/accounts
  tag: 8

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true
datasource_url: jdbc:mysql://accountsdb:3306/accountsdb

accountsdb:
  enabled: true
  name: accountsdb
  pvcName: accountsdb-pvc
  storage: 1Gi
  image:
    repository: mysql
    tag: "8"
  rootPassword: root
  database: accountsdb
  schema: |
    CREATE TABLE IF NOT EXISTS `customers` (
      `customer_id` int AUTO_INCREMENT  PRIMARY KEY,
      `name` varchar(100) NOT NULL,
      `email` varchar(100) NOT NULL,
      `mobile_number` varchar(20) NOT NULL,
      `created_at` date NOT NULL,
      `created_by` varchar(20) NOT NULL,
      `updated_at` date DEFAULT NULL,
      `updated_by` varchar(20) DEFAULT NULL
    );

    CREATE TABLE IF NOT EXISTS `accounts` (
      `customer_id` int NOT NULL,
      `account_number` int AUTO_INCREMENT  PRIMARY KEY,
      `account_type` varchar(100) NOT NULL,
      `branch_address` varchar(200) NOT NULL,
      `communication_sw` boolean,
      `created_at` date NOT NULL,
      `created_by` varchar(20) NOT NULL,
      `updated_at` date DEFAULT NULL,
      `updated_by` varchar(20) DEFAULT NULL
    );